.TH INTERNSCTL 1 "January 2024" "v0.1.0" "internsctl manual"

.SH NAME
internsctl \- custom command for managing interns

.SH SYNOPSIS
.B internsctl
[\fIOPTION\fR]...

.SH DESCRIPTION
This manual page documents the
.B internsctl
command. It is a versatile tool for managing intern-related tasks.

.SH OPTIONS
.TP
.B -v --version
Display the version information for internsctl.

.TP
.B -h --help
Display this help message.

.TP
.B cpu getinfo
Displays CPU information.

.TP
.B memory getinfo
Displays memory information.



.SH EXAMPLES
Display version information:
.B internsctl --version

Display help message:
.B internsctl --help

Display CPU information:
.B internsctl cpu getinfo

Display memory information:
.B internsctl memory getinfo

.SH AUTHOR
Written by Yash Chaudhary.

.SH SEE ALSO
.BR ls (1),
.BR grep (1).
